### ISSUE TITLE
sm_server_tier problem [BUG]

### ISSUE THREAD

**Issue by sashajov** [qawery-just-sad/surftimer-mapchooser#13]
**Describe the bug**
Just after reloading the nominations plugin sm_server_tier is working good, but after some time it stopped as you can see on the beginning of the video here: https://youtu.be/hbh8Do_EMek (Video will be available after 9:30PM UTC+2)

**How To Reproduce**
Also, I noticed that after installing the nominations plugin, nominations.cfg doesn't have sm_server_tier cvar. So I need to add manually. Maybe there is some issue, not sure :)

Is there maybe a way to add support for maplist, mapcycle or multi_server_mapcycle.txt, reading from database can be unstable cuz, for example, I have a lot of zoned maps not using actually. I know there is [fix](https://github.com/qawery-just-sad/surftimer-mapchooser/commit/919386394b4e170c289c672c2115aa8eb29d8ca9), but maybe it's not a bad idea to add this feature :)))

**Error Log**

Maybe this is somehow connected. I am not sure :)

`L 09/23/2020 - 18:48:14: [nominations.smx] [Nominations] SQL Error (SelectMapListCallback): Lost connection to MySQL server during query
L 09/23/2020 - 18:49:16: [mapchooser.smx] [Mapchooser] SQL Error (SelectMapListCallback): Lost connection to MySQL server during query`

**Screenshots** (video)
https://youtu.be/hbh8Do_EMek

**System Information:**
 - OS: CentOS 7
 - Mapchooser Version: 1.8

**Comment by qawery-just-sad** [comment]
> Set `sm_server_tier` in `csgo/cfg/sourcemod/mapchooser.cfg` to the tier of maps you want appearing the nominate list. Example, for a tier 1-3 server, set it to `sm_server_tier 1.3`, a tier 1 only server would be `sm_server_tier 1.0` and if you want all tiers `sm_server_tier 0`

As to the maplist ehh no

**Comment by qawery-just-sad** [comment]
I guess that closes the issue
