### ISSUE TITLE
[BUG] RTV max count from all players

### ISSUE THREAD

**Issue by KristianP26** [qawery-just-sad/surftimer-mapchooser#14]
RTV max count from all players when you limit players to use RTV by points.
It should be just from players what are possible to use RTV.

**Comment by qawery-just-sad** [comment]
Do you mind testing this branch and telling me if it works?
https://github.com/qawery-just-sad/surftimer-mapchooser/tree/fix-rtv-fixes

**Comment by KristianP26** [comment]
No problem

**Comment by qawery-just-sad** [comment]
This is a problem caused by surftimer itself, i could A. connect rtv to surftimer db to circumvent the issue or B. fix issue within my fork of surftimer.
Since I wrote in readme that i support most of the forks of surftimer I guess i have to go with first option
