### ISSUE TITLE
[BUG] Rank Requirement - Map change.

### ISSUE THREAD

**Issue by stunslave** [qawery-just-sad/surftimer-mapchooser#17]
**Describe the bug**
Setting a point or rank requirement... and then using RTV causes the server to set a nextmap.. without a mapvote. (the map doesn't change) This only happens when there are more than one player with the rank requirement connected to the server.  

**How To Reproduce**
1.  Set the rank requirement
2.  Get more than one player with the current rank requirement to connect to the server. [I have not tested with non rank/point requirement players]
3.  Type RTV
4.  The server sets the next map and the vote doesn't start.

**Screenshots**
![image](https://user-images.githubusercontent.com/47533535/117535481-3d49e280-aff6-11eb-8117-5f51f65ae4ed.png)
![image](https://user-images.githubusercontent.com/47533535/117535626-f3153100-aff6-11eb-8d41-d36d533378a4.png)

**System Information:**
 - Mapchooser Version: SurfTimer Mapchooser 1.8.3

**Comment by qawery-just-sad** [comment]
you sure that all plugins are version 1.8.3?

**Comment by qawery-just-sad** [comment]
I have tested this and I have not been able to reproduce the issue, try checking plugin versions with `sm plugins list`
If all of mapchooser plugins say 1.8.3 try restarting server, if that doesn't help i have no idea
