### ISSUE TITLE
[Suggestion] Tiers/Maps Nominate Only

### ISSUE THREAD

**Issue by stunslave** [qawery-just-sad/surftimer-mapchooser#3]
**This is a SUGGESTION!**
**Describe the solution you'd like**
I would like if possible to add **a cvar to set certain Tiers to nominate only.** 

The server can be running all maps but if a tier/map is set to Nominate Only, it wont show on map end vote unless it's been nominated.

**Comment by qawery-just-sad** [comment]
I think it's a bad idea to hide maps from players, especially when server covers all tiers.

**Comment by stunslave** [comment]
It allows hosts to run all maps on there servers, but keeps high tier maps only nominatable, this way the map end vote also doesn't get completely filled with tier 5 / tier 6 maps. Which tends to happen often with this plugin.

If this cant be done maybe force it so a map from each tier ends up on the endvote... So it doesnt just random a whole pile of maps from a single tier or 2.

Example:
Map Vote menu.
1. Random Tier 1 map.
2. Random Tier 2 map.
3. Random Tier 3 map.
4. Random Tier 4 map.
5. Random Tier 5 map.

Next page etc.

**Comment by qawery-just-sad** [comment]
In current state of this plugin neither of those options are possible (all 3 plugins would need a full rewrite).
I like the idea, but even better solution would be percentage for tier allocation.

## Example:
sm_tier_percent "50.30.20"
50% of all vote slots tier 1-2
30% of all vote slots tier 3-4
20% of all vote slots tier 5-8

1. Random Tier 1 map.
2. Random Tier 1 map.
3. Random Tier 2 map.
4. Random Tier 3 map.
5. Random Tier 4 map.
6. Random Tier 7 map.

Something like that. (still would need to rewrite whole plugin)
