### ISSUE TITLE
[Suggestion] Tier Categories Menu

### ISSUE THREAD

**Issue by stunslave** [qawery-just-sad/surftimer-mapchooser#5]
**Describe the solution you'd like**
If possible can you add a Tier Categories Menu when nominating a map.
Trying to nominate a tier 5-8 map can take a very long time because of how many lower tier maps there are.

**Additional context**
### Example:
_Type !nominate to bring up the menu below_

Nominate Tier:
**Tier 1
Tier 2
Tier 3
Tier 4
Tier 5
Tier 6
Tier 7
Tier 8**

_Then after if Tier 1 Selected_
**Nominate Map - Tier 1:
Map_name
Map_name
Map_name
Etc..**

Something like this.

**Comment by qawery-just-sad** [comment]
hey if you can't wait few more days for tier menus to be completely implemented then you can self compile this https://github.com/qawery-just-sad/surftimer-mapchooser/tree/tierd-of-this-menu
only issues rn are that sm_server_tier has to have value like this 1.1 (only tier 1), 2.2 (only tier 2), 1.4 (only tiers 1-4), 1.8 (all tiers)
and it also displays map tiers when in tier menu

**Comment by qawery-just-sad** [comment]
Closed by merging #11
