### ISSUE TITLE
[BUG] Check for maps in directory

### ISSUE THREAD

**Issue by dark-rage** [qawery-just-sad/surftimer-mapchooser#6]
Is it possible to add a check to "When the map is taken from database for nomination/voting list, it is checked if the MapExists in maps folder" ? The reason why it's required is... a lot of servers use pre-made zones which contains xyz random maps.

**Comment by HarunKilic** [comment]
Hi, about this request. I see that it is useful, but is it also possible to suppress the errors? I am using the pre-made zones, but i do not want to remove them incase i add them later on.

**Comment by qawery-just-sad** [comment]
can't you just use the [cleaner](https://forums.alliedmods.net/showthread.php?t=195008)?

**Comment by HarunKilic** [comment]
I am not familiar with cleaner plugin. Can u give an example of how i can suppress this message in the cleaner.txt file?

**Comment by dark-rage** [comment]
> 
> 
> I am not familiar with cleaner plugin. Can u give an example of how i can suppress this message in the cleaner.txt file?

[mapchooser.smx]
Add this to suppress map missing errors from this plugin.

You can also add "Error 404" in case the above doesn't works for you.

**Comment by HarunKilic** [comment]
allright, thanks! 👍
